# Use custom format
format = """
[┌───────────────────>](bold green)
[│](bold green)$directory$git_branch$git_commit$git_state$git_status$rust$package
[└─>](bold green) """

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
