format = """
$battery\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$line_break\
$nix_shell\
$python\
$character"""

[battery]
full_symbol = "•"
charging_symbol = "⇡"
discharging_symbol = "⇣"

[directory]
read_only = " 󰌾"
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = ""
"Pictures" = ""

[git_branch]
symbol = ""
format = "[$symbol$branch]($style)"
style = "bright-black"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[character]
success_symbol = "[❯](bold blue)[❯](bold cyan)[❯](bold white)"
error_symbol = "[❯](red)[❯](red)[❯](red)"
vimcmd_symbol = "[❮](bold green)"

[nix_shell]
symbol = " "
format = '[$symbol(\($name\)) ]($style)'
style = "bold blue"

[python]
symbol = " "
format = '[$symbol(\($virtualenv\)) ]($style)'
style = "bold yellow"
