# Custom 'zshrc' managed by Nix    # -*- mode:sh; -*-

# History settings
HISTFILE="${HOME}/.zhistory"
HISTSIZE=10000
SAVEHIST=10000
setopt append_history              # allow multiple sessions to append to one history
setopt bang_hist                   # treat ! special during command expansion
setopt extended_history            # Write history in :start:elasped;command format
setopt hist_expire_dups_first      # expire duplicates first when trimming history
setopt hist_find_no_dups           # When searching history, don't repeat
setopt hist_ignore_dups            # ignore duplicate entries of previous events
setopt hist_ignore_space           # prefix command with a space to skip it's recording
setopt hist_reduce_blanks          # Remove extra blanks from each command added to history
setopt hist_verify                 # Don't execute immediately upon history expansion
setopt inc_append_history          # Write to history file immediately, not when shell quits
setopt share_history               # Share history among all sessions

# Tab completion
setopt complete_in_word            # cd /ho/sco/tm<TAB> expands to /home/scott/tmp
setopt auto_menu                   # show completion menu on succesive tab presses
setopt autocd                      # cd to a folder just by typing it's name
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&' # These "eat" the auto prior space after a tab complete

# Misc
setopt NO_BEEP                     # no beeping
setopt NO_LIST_BEEP                # no beeping for ambiguous completion
setopt NO_HIST_BEEP                # not for history errors either
setopt interactive_comments        # allow # comments in shell; good for copy/paste
unsetopt correct_all               # I don't care for 'suggestions' from ZSH
export BLOCK_SIZE="'1"             # Add commas to file sizes

# Path
typeset -gU cdpath fpath mailpath path # keep duplicates out of the path arrays

# Completions for nix-installed packages
if [ -d "$HOME/.nix-profile/share/zsh/site-functions/" ]; then
    fpath=("$HOME/.nix-profile/share/zsh/site-functions/" $fpath)
fi

# Load completions
autoload -Uz compinit && compinit

# Bindkey
bindkey -e
bindkey '\e[3~' delete-char
bindkey '^p' history-search-backward
bindkey '^n' history-search-forward
bindkey ' '  magic-space

# Less settings
#
# -F    exit if the file can be displayed in one screen
# -g    highlight only the particular string found by the last search command
# -i    ignore case in search commands unless an uppercase letter is present
# -M    prompt more verbosely
# -R    display ANSI "color" escape sequences in their raw form
# -S    chop long lines (instead of wrapping)
# -W    highlight the first "new" line after forward movement
# -X    disables clearing the screen after exiting
# -x4   display tabs as 4-character width
# -z-4  always keep 4 lines overlapping with the previous screen
export LESS='-F -g -i -M -R -S -W -X -x4 -z-4'

# Set colors for less (see https://wiki.archlinux.org/index.php/Color_output_in_console#less)
export LESS_TERMCAP_mb=$'\E[31m'    # begin bold
export LESS_TERMCAP_md=$'\E[34m'    # begin blink
export LESS_TERMCAP_me=$'\E[0m'     # reset bold/blink
export LESS_TERMCAP_so=$'\E[32m'    # begin reverse video
export LESS_TERMCAP_se=$'\E[0m'     # reset reverse video
export LESS_TERMCAP_us=$'\E[33m'    # begin underline
export LESS_TERMCAP_ue=$'\E[0m'     # reset underline

# Colorize less output for source code if GNU source-highlight is installed
if (( $+commands[source-highlight-esc.sh] )); then
    export LESSOPEN="|source-highlight-esc.sh %s 2>/dev/null"
fi

# Source local zshrc if present
test -s "$HOME/.zshrc.local" && source "$HOME/.zshrc.local"

# Git settings
if (( $+commands[hub] )); then
    eval "$(hub alias -s)"
fi

# Aliases
alias gs='git status -sb'
alias gl='git log'
alias gll='git loglines'
alias gd='git diff'

alias gco='git checkout'
alias gcb='git checkout -b'

alias gup='git pull --rebase'
alias grv='git remote -v'

# Fasd settings
if (( $+commands[fasd] )); then
    eval "$(fasd --init auto)"

    # Default aliases, included here for documentation
    # alias a='fasd -a'        # any
    # alias s='fasd -si'       # show / search / select
    # alias d='fasd -d'        # directory
    # alias f='fasd -f'        # file
    # alias sd='fasd -sid'     # interactive directory selection
    # alias sf='fasd -sif'     # interactive file selection
    # alias z='fasd_cd -d'     # cd, same functionality as j in autojump
    # alias zz='fasd_cd -d -i' # cd with interactive selection
fi

# Emacs aliases
alias emacs='emacsclient --no-wait --create-frame'
alias e=emacs

# Nix aliases
alias ns='nix-shell'
alias ne='nix-env'

alias nixfind='nix-env -qaP'
alias nixinfo='nix-env -qa --description'
alias nixopps='nix-env --rollback'

# GNU and BSD (macOS) ls use different flags
if $(ls --version &>/dev/null); then
    lsflags="--color=auto --group-directories-first"
else
    lsflags="-G"
    export CLICOLOR=1
fi

# Aliases
alias ls="ls ${lsflags}"        # use color
alias ll="ls ${lsflags} -lh"    # show human readable sizes
alias la="ls ${lsflags} -lhA"   # show all files (except . and ..)
alias lt="ls ${lsflags} -lhtr"  # show by date modified (oldest first)
alias l="ll"                    # pacify the monster

# Colorize some programs if ~/.dircolors exists
if (( $+commands[dircolors] )); then
    test -r $HOME/.dircolors && eval "$(dircolors $HOME/.dircolors)"

    # Colorify other things
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Safety first…
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Misc
alias mkdir='mkdir -p'
alias du='du -h'
alias ..='cd ../.'
alias ...='cd ../../.'
alias ....='cd ../../../.'
alias .....='cd ../../../../.'

# Prompt initialization
eval "$(starship init zsh)"
